#!/bin/bash

[ ! -d DEBIAN ] && echo "Please cd in yasa new version and then run install script again" && exit 1

/bin/cp -a sbin/yasa /sbin/yasa
/bin/cp -ar usr/lib/yasa /usr/lib/
/bin/cp -ar usr/share/doc/yasa /usr/share/doc/
/bin/cp -ar etc/yasa/skell /etc/yasa/
