#!/bin/bash

# gmagr script for manage groups in yasa
# Usage: log <script_name> <severity> <message>
#
# log message example: Yasa[script_name]: severity: Message here
# Version number (may use later)
version=0.1

# System variable
source /etc/default/yasa

script_name=$1
severity=$2
shift 2
message="$@"

usage() {
    echo "Usage: log <script_name> <severity> <message>"

    return 0
}

if [ -z "$severity" -o -z "$(echo $severity | grep "info\|debug\|warn\|error")" ] 
then
    usage
    exit 1
fi

logger -p local0.$severity "Yasa[$script_name]: $message"

exit 0
