#!/bin/bash

# This script is based on IOI organization request for control on USB connections 
# and devices. 
# Copyright (C) 2016 Behrad Eslamifar <b.eslamifar@cvak.ir> and IOI
# This is properitary software and cant freely distributed.
# Version number (may use later)

# Default config
source /etc/default/yasa

usage() {
        echo "Usage: /usr/lib/yasa/sbin/yasa <auth> <device_path> <0|1>" 1>&2
        echo "          0: Open USB device, 1: Block USB device" 1>&2
}

yasa_cron() {
        # temperorly file 
        TEMP=$(mktemp /tmp/usb.XXXXXXXX)

        # trap and delete temp file
        trap "rm $TEMP; exit" SIGHUP SIGINT SIGTERM

	# save current time
	local currenttime=$(date +"%s")

	# variable for save dev.allow line
	local scomment
	local ucomment
	local line

	# remove dev allow rule based on expire time
	for host_dir in "$CLIENTHOME/*"
	do
		if [ -d "$host_dir" ]
		then
			while read line
			do
				if [ ! -z "$(echo $line | grep "^# comment")" ]
				then
					ucomment=$line
				elif [ ! -z "$(echo $line | grep "^# From:")" ]
				then
					scomment=$line
				elif [ ! -z "$(echo $line | grep "^[0-9]" )" ]
				then
					if [ ! -z "$(echo $line  | awk '($1 > value ) ' value=$currenttime)" -o "$(echo $line | awk '{ print ( $1 ) }')" == "0" ]
					then
						echo -e "$ucomment\n$scomment\n$line" >> $TEMP
					fi
				else
					echo $line >> $TEMP
				fi
			done < $host_dir/temp/$WDEVICE
			cp $TEMP $host_dir/temp/$WDEVICE
		else
			continue
		fi

		# write rule for each
		host_write_rule $hostid

		# deploy rule for each host
		host_deploy_config $hostid
	done

	# remove class based on expire time
	# not implemented

	# remove temp file
	[ -f "$TEMP" ] && rm $TEMP

}

yasa_auth() {
	local name=/sys$1
	local value=$2
	echo "$value" > "${name%/*}/authorized" 2>> /dev/null
	echo "${name%/*}/authorized" >> /var/log/yasa-auth.log
	return 0
}

if [ ! -z "$1" ]
then
    if [ "$1" = "cron" ]
    then
    	yasa_cron
    elif [ "$1" = "auth" ]
    then
    	yasa_auth $2 $3
    else
            usage
            exit 1
    fi
else
        usage
        exit 1
fi


