#!/bin/bash

set -e

puppet_modules_dir=/etc/puppetlabs/code/environments/production/modules/

chmod 755 /etc/yasa/{group,puppet,skell}
chmod 755 /etc/yasa/skell/{etc,group,temp}
chmod 755 /etc/yasa/puppet/{files,manifests,templates}

if [ -d "$puppet_modules_dir" ]
then
    if [ -L "$puppet_modules_dir/yasa" ] 
    then
    	link=$(readlink $puppet_modules_dir/yasa)
    	if [ "$link" == "/etc/yasa/puppet" ]
    	then
    		echo "Do nothing" > /dev/null
    	else
    		rm -r $puppet_modules_dir/yasa
     		ln -s /etc/yasa/puppet $puppet_modules_dir/yasa
    	fi
    elif [ -e $puppet_modules_dir/yasa ]
    then
    	rm -r $puppet_modules_dir/yasa
     	ln -s /etc/yasa/puppet $puppet_modules_dir/yasa
    else
    	ln -s /etc/yasa/puppet $puppet_modules_dir/yasa
    fi
else
    mkdir -p $puppet_modules_dir

    if [ -L "$puppet_modules_dir/yasa" ] 
    then
    	link=$(readlink $puppet_modules_dir/yasa)
    	if [ "$link" == "/etc/yasa/puppet" ]
    	then
    		echo "Do nothing" > /dev/null
    	else
    		rm -r $puppet_modules_dir/yasa
     		ln -s /etc/yasa/puppet $puppet_modules_dir/yasa
    	fi
    elif [ -e "$puppet_modules_dir/yasa" ]
    then
    	rm -r $puppet_modules_dir/yasa
     	ln -s /etc/yasa/puppet $puppet_modules_dir/yasa
    else
    	ln -s /etc/yasa/puppet $puppet_modules_dir/yasa
    fi
fi

# genrate ssh key for yasaclient deployment
if [ ! -f "/etc/yasa/keys/server" -a ! -f "/etc/yasa/keys/server.pub" ]
then
    echo "Generating SSH keys ..."
    echo "..."
    ssh-keygen -f /etc/yasa/keys/server -N '' > /dev/null 2>&1
    echo "SSH keys generated successfuly ..."
else
    echo "Key(s) exist. if you want create new keys, try from Yasa Management and Utility Menu"
fi

exit 0
